@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

' LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Container diagram for Vacation creation system

Person(customer, "Сотрудник организации", "Штатный сотрудник")
Person_Ext(customer_zup, "Рассчетчик", "Рассчитывает и выплачивает заработную плату")

System_Boundary(lk_system, "Личный кабинет сотрудника") {
    Container(web_app, "Web Application", "1с веб клиент", "Позволяет работать с системой через веб приложение")
    Container(spa, "Тонкий клиент", "1С клиент", "Позволяет работать с системой через десктоп приложение")
    Container(server_1c, "Сервер 1с", "Кластер серверов", "Позволяет работать с базой данных, компонентами, API")
    ContainerDb(database, "Database", "SQL Database", "Система управления базой данных")
    Container(backend_api, "Веб сервер", "Apach", "Доступ к 1С через веб, публикация http сервисов")
}

System_Ext(zup_system, "1C ЗУП", "Позволяет вести  кадровый учет и рассчитывать зарплату")
System(broker_system, "Брокер сообщений", "Rаbbit MQ")

Rel(customer, web_app, "Uses", "HTTPS")
Rel(customer, spa, "Uses", "TCP/HTTPS")

Rel(customer_zup, zup_system, "Uses")

Rel(web_app, backend_api, "Uses","HTTPS")
Rel(spa, backend_api, "Uses","HTTPS")
Rel(backend_api, server_1c, "","HTTPS")
Rel_Back(backend_api, server_1c, "","HTTPS")
Rel(spa, server_1c, "","TCP")
Rel(server_1c, database, "", "TCP")


Rel_Neighbor(server_1c, broker_system, "Данные об отпусках", "async, JSON/HTTPS")
Rel_Neighbor(zup_system, broker_system, "Чтение данных об отпусках", "async, JSON/HTTPS")

Rel(zup_system, backend_api,"Uses, Данные о сотрудниках", "sync, JSON/HTTPS")


@enduml