'>>> библиотека 1ce-icons-for-plantuml (ext)
!define v8_PUML https://raw.githubusercontent.com/plastinin/1ce-icons-for-plantuml/extended/dist/
!include v8_PUML/common.puml
!include v8_PUML/v8_AccRg.puml
!include v8_PUML/v8_Document.puml
!include v8_PUML/v8_Catalog.puml
!include v8_PUML/v8_InfoRg.puml
!include v8_PUML/v8_ChartsOfCharacteristicTypes.puml
!include v8_PUML/v8_DefinedTypes.puml
!include v8_PUML/v8_Enum.puml
'<<<

title Обмен данными по отпуску

caption Интеграция с 1С:ЗУП

package 1C_ЛК <<Rectangle>> #ffff99 {

_Документ(ЗаявкаНаОтпуск, "Заявка на отпуск") {
	 {static} Ссылка
	 {static} Сотрудник
     {static} ВидОтпуска
	 {static} ДатаНачала
	 {static} ДатаОкончания
     {static} Согласующий
 	 {static} Согласован
}

_Справочник(Сотрудники, "Сотрудники") {
	 {static} Ссылка
	 {static} Код
     {static} Наименование
}
_Справочник(ВидыОтпусков, "Виды отпусков") {
	 {static} Ссылка
     {static} Наименование
}

_Справочник(Пользователи, "Пользователи") {
	 {static} Ссылка
	 {static} Код
     {static} Наименование
	 {static} Сотрудник
	 {static} Руководитель
}
_Справочник(Задача, "Задача") {
	 {static} Ссылка
	 {static} Номер
     {static} Наименование
	 {static} Дата
	 {static} БизнесПроцесс
	 {static} Выполнена
	 {static} Сотрудник
}

_Справочник(СогласованиеОтпуска, "БП Согласование отпуска") {
	 {static} Ссылка
	 {static} Номер
     {static} Наименование
	 {static} Дата
	 {static} Стартован
	 {static} Завершен
	 {static} ПроверкаСогласования
	 {static} Сотрудник
	 {static} ДокументНаСогласование
	 {static} Инициатор
}
_РегистрСведений(СведенияПоАдресации, "Сведения по адресации") {
	 {static} Сотрудник
	}
}

package 1С_ЗУП <<Rectangle>> #008000 {

    _Документ(ПриказНаОтпуск, "Приказ на отпуск") {
	 {static} Ссылка
	 {static} Сотрудник
     {static} Статус
	 {static} ДатаНачала
	 {static} ДатаОкончания
	 {static} КоличествоДней
	 {static} Рассмотрел
	 {static} ДатаРассмотрения
	 {static} Комментарий
}

}

Пользователи-->Сотрудники:Сотрудник:Ссылка
Пользователи-->Пользователи:Руководитель:Ссылка
ЗаявкаНаОтпуск-->Пользователи:Согласующий:Ссылка
ЗаявкаНаОтпуск-->Сотрудники:Сотрудник:Ссылка
ЗаявкаНаОтпуск-->ВидыОтпусков:ВидОтпуска:Ссылка
СогласованиеОтпуска-->Сотрудники:Сотрудник:Ссылка
СогласованиеОтпуска-->Пользователи:Инициатор:Ссылка
СогласованиеОтпуска-->ЗаявкаНаОтпуск:ДокументНаСогласование:Ссылка
Задача-->Сотрудники:Сотрудник:Ссылка
Задача-->СогласованиеОтпуска:БизнесПроцесс:Ссылка
Задача-->СведенияПоАдресации:Сотрудник:Ссылка
СведенияПоАдресации-->Сотрудники:Сотрудник:Ссылка

ЗаявкаНаОтпуск-->ПриказНаОтпуск:Ссылка::Номер
ЗаявкаНаОтпуск-->ПриказНаОтпуск:Сотрудник::Код
ЗаявкаНаОтпуск-->ПриказНаОтпуск:ВидОтпуска::Наименование
